# Imports timeseries module from environment package
from context import timeseries

# Imports other required modules for this example
import pandas as pd
import os
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

try: 
	# Reads the pickle dataframe generated by the example_usgs.py script
	flow_df = pd.read_pickle(os.path.join('./','data_files/ILState03612600_UTC.pkl'))
except:
	print("=== Error: File  \"data_files/ILState03612600_UTC.pkl \" could not be found!                ===" )
	print("=== Make sure to first run the script  \"example_usgs.py \"  to download required file. ===" )
	exit()

# Creates a missing samples report for the input dataframe
missing_sample_report = timeseries.missingsamples(flow_df, verbose=True)

# Creates an one-minute linearly interpolated time series
resampled_df = timeseries.resampledf(flow_df, interp_method='linear', verbose=True)

# Plots resampled data
resampled_df[:20000].plot()
plt.title("Flow Velocity for USGS Site 03612600")
plt.xlabel("Timestamp")
plt.ylabel("Flow Velocity in Feet/sec")
plt.legend(loc='upper right')
plt.show()
